### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by marph91** [Dobatymo/rbtv-api#1]
Hi, thanks for this nice project!

I have some improvement/style suggestions:

* Use four space indentation instead of tabs (https://www.python.org/dev/peps/pep-0008/#indentation). Probably even use black for code formatting and add a pre commit check.
* Type hints can be made inline. Imo. this looks neater than specifying the hints it in an separate comment.
* There are no tests. Implement a testsuite based on unittest or pytest and run it as an github action.
* There are no examples in the readme. Add a few.
* Some more, but it would be too much for this issue.

The changes wouldn't affect the user interface much. However, they would touch almost all of the existing code. To get an idea how the code would look like, you can take a look [here](https://github.com/marph91/joppy/blob/master/joppy/api.py). I thought about creating a separate repo, but maybe we can rather bundle the efforts. Let me know if you are interested or if you want to keep the project as is.

**Comment by Dobatymo** [comment]
@marph91 Thank you for your feedback. So far I was probably the only user of this library. So I didn't put much thought into it. But if someone else has interest in it, I will try to improve it.

**Comment by marph91** [comment]
Thanks for the fast reply. The changes are looking fine!

For now I'm not using the API for a specific application. Just exploring a bit. I will open an issue or PR if I find some issue.
